stages:
- tests
- build

test:ltr:
  stage: tests
  script:
    - make docker-test FLAVOR=ltr
  tags:
    - factory

test:release:
  stage: tests
  script:
    - make docker-test FLAVOR=release
  tags:
    - factory

test:3.4:
  stage: tests
  script:
    - make docker-test FLAVOR=3.4
  tags:
    - factory

build:
  stage: build
  script:
    - make dist deliver
  tags:
    - factory

