stages:
- tests
- build

test:ltr:
  stage: tests
  script:
    - make docker-test FLAVOR=ltr PYQGSWPS_MAX_VERSION=1.5
  tags:
    - factory

test:release:
  stage: tests
  script:
    - make docker-test FLAVOR=release
  tags:
    - factory

build:
  stage: build
  script:
    - make dist deliver
  tags:
    - factory

